### ISSUE TITLE
`pennylane-lightning-core` is broken on osx-arm64

### ISSUE THREAD

**Issue by leofang** [conda-forge/pennylane-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```python
>>> import pennylane_lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leof/miniforge3/envs/pny/lib/python3.10/site-packages/pennylane_lightning/__init__.py", line 17, in <module>
    from .lightning_qubit import LightningQubit
  File "/Users/leof/miniforge3/envs/pny/lib/python3.10/site-packages/pennylane_lightning/lightning_qubit.py", line 47, in <module>
    from .lightning_qubit_ops import (
ImportError: dlopen(/Users/leof/miniforge3/envs/pny/lib/python3.10/site-packages/pennylane_lightning/lightning_qubit_ops.cpython-310-darwin.so, 2): no suitable image found.  Did find:
	/Users/leof/miniforge3/envs/pny/lib/python3.10/site-packages/pennylane_lightning/lightning_qubit_ops.cpython-310-darwin.so: mach-o, but wrong architecture
	/Users/leof/miniforge3/envs/pny/lib/python3.10/site-packages/pennylane_lightning/lightning_qubit_ops.cpython-310-darwin.so: mach-o, but wrong architecture
```

I guess there might be some CMake flags that I didn't set up right in #20 for cross compilation... 😞

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by leofang** [comment]
Submitted https://github.com/conda-forge/admin-requests/pull/703 to mark the osx-arm64 packages as broken.
